#!/usr/bin/env Rscript
# Project: repotools
# 
# Author: Renaud Gaujoux
#
# R script to run as a cron job to update
#
# Created: Jul 21, 2014
###############################################################################

# process command line arguments
args <- commandArgs(TRUE)
getArg <- function(x, default = NULL){
    if( length(i <- which(args == x)) ){
		if( length(args) > i && !grepl("^-", args[i+1L]) ) args[i+1L]
		else TRUE
    }else default
}

devel <- getArg("--devel", FALSE)
force <- getArg("--force", FALSE)
reinstall <- getArg("--init", FALSE)

# update repotools
if( !devel ){
	if( reinstall ) remove.packages('repotools')
	dump <- capture.output(source("http://renozao.github.io/repotools/install.R"))
}else{
	#source("pkg/inst/www/repotools.R")
	dump <- suppressMessages(l('repotools', quiet = TRUE))
}

# genererate repository from source github/src/contib directory
src <- normalizePath(getArg('--src', 'repos/github/src/contrib'))
out <- getArg('--out', '.')

updated_repo_path <- repotools:::GRAN.update(src, out, force = force, verbose = TRUE)
cat(updated_repo_path)
